# Generated by Django 5.1.1 on 2024-10-09 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('techy_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='category',
        ),
    ]
